### ISSUE TITLE
Any way to use this library in Angular?

### ISSUE THREAD

**Issue by Hanzofm** [puffinsoft/jscanify#15]

**Comment by ColonelParrot** [comment]
No specific Angular support right now, but it's [probably possible](https://stackoverflow.com/questions/51484076/angular-include-cdn-in-component-usage)

**Comment by sasankaweera123** [comment]
If it will be support for angular [ TS ] will be great.

**Comment by ColonelParrot** [comment]
@sasankaweera123 good idea. I'll take a deeper look, but it doesn't look like OpenCV.js has great support for TS right now. Will need to pay close attention to this thread https://github.com/opencv/opencv/issues/15306
