### ISSUE TITLE
Error importing jscanify library in React application

### ISSUE THREAD

**Issue by Hadi311374** [puffinsoft/jscanify#26]
I'm experiencing an issue when trying to import and use the jscanify library in a React application. While the CDN approach works fine, importing the library as a module using the `import` statement causes an error.

import React, { useEffect, useRef, useState } from 'react';
import jscanify from 'jscanify';

export default function PaperScanner() {
  const canvasRef = useRef(null);
  const [photoData, setPhotoData] = useState(null);

  useEffect(() => {
    const scanner = new jscanify(); // <-- Error occurs here
   
  }, []);
  
}

Error Message:
TypeError: Cannot set property document of #<Window> which has only a getter

**Comment by ColonelParrot** [comment]
It has to be imported through the html file. See [react-scanify-demo](https://github.com/ColonelParrot/react-scanify-demo)

**Comment by Hadi311374** [comment]
In this use CDN

**Comment by ColonelParrot** [comment]
Yes, unfortunately I haven't had the opportunity to add React support 😔
